\version "2.24.0"

#(set-global-staff-size 36)

\header {
  title = "Menuet in G"
  subtitle = "AutoPage test fixture — generated by tools/make_fixture.py"
  composer = "in the style of the Petzold minuet, BWV Anh. 114"
  tagline = ##f
}

\paper {
  #(set-paper-size "a4")
  systems-per-page = #2
  print-page-number = ##t
}

melody = {
  \clef treble
  \key g \major
  \time 3/4
  d''4 g'8 a'8 b'8 c''8 |
    d''4 g'4 g'4 |
    e''4 c''8 d''8 e''8 fis''8 |
    g''4 g'4 g'4 |
    c''4 d''8 c''8 b'8 a'8 |
    b'4 c''8 b'8 a'8 g'8 |
    a'4 b'8 a'8 g'8 fis'8 |
    g'2. |
    d''4 g'8 a'8 b'8 c''8 |
    d''4 g'4 g'4 |
    e''4 c''8 d''8 e''8 fis''8 |
    g''4 g'4 g'4 |
    c''4 b'8 a'8 g'8 fis'8 |
    e''4 d''8 c''8 b'8 a'8 |
    fis'4 g'8 a'8 b'8 g'8 |
    a'2. |
    b''4 g''8 a''8 b''8 g''8 |
    a''4 d''8 e''8 fis''8 g''8 |
    a''4 fis''8 g''8 a''8 fis''8 |
    g''4 b'4 b'4 |
    e''4 fis''8 g''8 a''8 b''8 |
    a''4 g''8 fis''8 e''8 d''8 |
    c''4 b'8 c''8 d''8 e''8 |
    d''2. |
    b''4 g''8 a''8 b''8 g''8 |
    a''4 d''8 e''8 fis''8 g''8 |
    a''4 fis''8 g''8 a''8 fis''8 |
    g''4 b'4 b'4 |
    c''4 d''8 e''8 fis''8 g''8 |
    a''4 g''8 fis''8 e''8 d''8 |
    b'4 c''8 b'8 a'8 fis'8 |
    g'2. |
}

bass = {
  \clef bass
  \key g \major
  \time 3/4
  g2. |
    g2. |
    c'2. |
    b2. |
    a2. |
    g2. |
    d2. |
    g2. |
    g2. |
    g2. |
    c'2. |
    b2. |
    a2. |
    g2. |
    d2. |
    d2. |
    g2. |
    d2. |
    d2. |
    g2. |
    c'2. |
    d2. |
    g2. |
    d2. |
    g2. |
    d2. |
    d2. |
    g2. |
    c'2. |
    d2. |
    d2. |
    g2. |
}

\score {
  \new PianoStaff <<
    \new Staff \melody
    \new Staff \bass
  >>
  \layout { }
}
