"""Generate the test fixture: a four-page score and audio of the same music.

Both come from one note list, so the recording and the engraving cannot drift
apart. The music is deliberately non-repetitive — an eight-bar phrase repeated
four times would make every page end sound identical, which is the one case the
matcher cannot resolve on audio alone.

    python3 tools/make_fixture.py

Writes fixtures/menuet-in-g.pdf (via LilyPond) and fixtures/menuet-in-g.wav.
"""

import math
import pathlib
import struct
import subprocess
import wave

BPM = 120
SR = 44100
OUT = pathlib.Path(__file__).resolve().parent.parent / "fixtures"

Q, E, H3 = 1.0, 0.5, 3.0  # quarter, eighth, dotted half — beats

# (midi, beats). Bars are separated for readability only.
MELODY = [
    # A
    [(74, Q), (67, E), (69, E), (71, E), (72, E)],
    [(74, Q), (67, Q), (67, Q)],
    [(76, Q), (72, E), (74, E), (76, E), (78, E)],
    [(79, Q), (67, Q), (67, Q)],
    [(72, Q), (74, E), (72, E), (71, E), (69, E)],
    [(71, Q), (72, E), (71, E), (69, E), (67, E)],
    [(69, Q), (71, E), (69, E), (67, E), (66, E)],
    [(67, H3)],
    # A' — same opening, new cadence, ends on the dominant
    [(74, Q), (67, E), (69, E), (71, E), (72, E)],
    [(74, Q), (67, Q), (67, Q)],
    [(76, Q), (72, E), (74, E), (76, E), (78, E)],
    [(79, Q), (67, Q), (67, Q)],
    [(72, Q), (71, E), (69, E), (67, E), (66, E)],
    [(76, Q), (74, E), (72, E), (71, E), (69, E)],
    [(66, Q), (67, E), (69, E), (71, E), (67, E)],
    [(69, H3)],
    # B — contrasting, an octave up
    [(83, Q), (79, E), (81, E), (83, E), (79, E)],
    [(81, Q), (74, E), (76, E), (78, E), (79, E)],
    [(81, Q), (78, E), (79, E), (81, E), (78, E)],
    [(79, Q), (71, Q), (71, Q)],
    [(76, Q), (78, E), (79, E), (81, E), (83, E)],
    [(81, Q), (79, E), (78, E), (76, E), (74, E)],
    [(72, Q), (71, E), (72, E), (74, E), (76, E)],
    [(74, H3)],
    # B'
    [(83, Q), (79, E), (81, E), (83, E), (79, E)],
    [(81, Q), (74, E), (76, E), (78, E), (79, E)],
    [(81, Q), (78, E), (79, E), (81, E), (78, E)],
    [(79, Q), (71, Q), (71, Q)],
    [(72, Q), (74, E), (76, E), (78, E), (79, E)],
    [(81, Q), (79, E), (78, E), (76, E), (74, E)],
    [(71, Q), (72, E), (71, E), (69, E), (66, E)],
    [(67, H3)],
]

# One root per bar.
BASS_ROOTS = [
    55, 55, 60, 59, 57, 55, 50, 55,
    55, 55, 60, 59, 57, 55, 50, 50,
    55, 50, 50, 55, 60, 50, 55, 50,
    55, 50, 50, 55, 60, 50, 50, 55,
]
BASS = [[(r, H3)] for r in BASS_ROOTS]

NAMES = ["c", "cis", "d", "dis", "e", "f", "fis", "g", "gis", "a", "ais", "b"]
DURS = {Q: "4", E: "8", H3: "2."}


def ly_note(midi, beats):
    ticks = "'" * (midi // 12 - 4)  # c' is middle C (MIDI 60)
    return NAMES[midi % 12] + ticks + DURS[beats]


def ly_voice(bars):
    return " |\n    ".join(" ".join(ly_note(m, b) for m, b in bar) for bar in bars)


def write_ly(path):
    path.write_text(f"""\\version "2.24.0"

#(set-global-staff-size 36)

\\header {{
  title = "Menuet in G"
  subtitle = "AutoPage test fixture — generated by tools/make_fixture.py"
  composer = "in the style of the Petzold minuet, BWV Anh. 114"
  tagline = ##f
}}

\\paper {{
  #(set-paper-size "a4")
  systems-per-page = #2
  print-page-number = ##t
}}

melody = {{
  \\clef treble
  \\key g \\major
  \\time 3/4
  {ly_voice(MELODY)} |
}}

bass = {{
  \\clef bass
  \\key g \\major
  \\time 3/4
  {ly_voice(BASS)} |
}}

\\score {{
  \\new PianoStaff <<
    \\new Staff \\melody
    \\new Staff \\bass
  >>
  \\layout {{ }}
}}
""")


def render_note(buf, start, midi, seconds, gain):
    """A few harmonics with a plucked-ish envelope — enough for a chroma test."""
    freq = 440.0 * 2 ** ((midi - 69) / 12)
    n = int(seconds * SR)
    for i in range(n):
        t = i / SR
        env = math.exp(-2.5 * t / seconds) * min(1.0, i / 400) * min(1.0, (n - i) / 400)
        s = (
            math.sin(2 * math.pi * freq * t)
            + 0.45 * math.sin(4 * math.pi * freq * t)
            + 0.2 * math.sin(6 * math.pi * freq * t)
        )
        j = start + i
        if j < len(buf):
            buf[j] += gain * env * s


def write_wav(path):
    spb = 60.0 / BPM
    total = int(sum(sum(b for _, b in bar) for bar in MELODY) * spb * SR) + SR
    buf = [0.0] * total

    for voice, gain in ((MELODY, 0.30), (BASS, 0.22)):
        t = 0.0
        for bar in voice:
            for midi, beats in bar:
                render_note(buf, int(t * SR), midi, beats * spb * 0.95, gain)
                t += beats * spb

    peak = max(abs(v) for v in buf) or 1.0
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(b"".join(
            struct.pack("<h", int(max(-1.0, min(1.0, v / peak * 0.89)) * 32767)) for v in buf
        ))


if __name__ == "__main__":
    import sys

    OUT.mkdir(exist_ok=True)
    # --audio-only skips LilyPond, so the audio can be regenerated anywhere the
    # standard library runs. The PDF is committed; the WAV is too big to be.
    if "--audio-only" not in sys.argv:
        ly = OUT / "menuet-in-g.ly"
        write_ly(ly)
        subprocess.run(["lilypond", "-o", str(OUT / "menuet-in-g"), str(ly)], check=True)
    write_wav(OUT / "menuet-in-g.wav")
    print("wrote", OUT / "menuet-in-g.wav")
